[구현&코너케이스] 9월 20일
Altu-Bitu-3/Altu-Bitu-Eunseo pull request #7
Opened 2022-09-25 23:41 UTC by Lisa-Tera

내용 & 질문

> 제출합니다!

<기존 제출>

> 1316,2840,3226,5397번 

<추가 제출>

2022-09-26 06:56 UTC, dooli1971039 requested changes
**p1. 2840 코드 리뷰 완료**
안녕하세요 은서님~
백준을 확인해보니 2840 문제를 틀리셨더라구요. 코드를 읽어보니, 알파벳 중복체크를 안 하신 것 같습니다. 한 바퀴 안에는 같은 알파벳이 여러번 들어갈 수 없어요. 이 부분 체크해주시면 될 것 같습니다.
궁금한 점 있으시면 리뷰어를 호출해주세요~
수고하셨습니다!!

2022-09-26 06:56 UTC, dooli1971039 commented on [구현&코너케이스] 9월 20일/2840.cpp
> +	}
p3. 입력을 저장하기 위해, 이차원 배열을 이용하셨네요! `vector<pair<int, char>> arr(25);` 를 사용해도 좋을 것 같습니다.

2022-09-26 09:05 UTC, flowersayo reviewed
**1316 코드리뷰 완료**

안녕하세요 은서님~!
정말 새로운 풀이 잘 구경하다 갑니다 🥺👍
p1 코멘트는 꼭 수정해주셨으면 하는 부분이고, p2/p3는 참고만해주셔도 괜찮습니다!
이번 구현 코너케이스 과제도 정말 수고 많으셨습니다!🥰

2022-09-26 09:05 UTC, flowersayo commented on [구현&코너케이스] 9월 20일/1316.cpp
> +		word.erase(unique(word.begin(), word.end()), word.end());//abcb�� earse�� �ߺ��� ���
오오 unique를 사용하면 벡터의 중복원소 제거가 편리하군요!!!! 은서님 덕분에 저도 배워가네요😊

2022-09-26 09:05 UTC, flowersayo commented on [구현&코너케이스] 9월 20일/1316.cpp
> +	for(int i=0; i<n; i++){
우와.. 이렇게 풀이하는 방식은 처음보는데 이방법은 정말 신선(?) 하네요!

2022-09-26 13:30 UTC, Dong-droid commented
**p3. 5397 코드 리뷰 완료**
먼저 수고하셨습니다!
stack으로 구현하기가 좀 까다로운 문제였는데 너무 잘 푸신 것 같습니다!
다른 풀이 방법으로 list를 사용할 수도 있어요 왜냐하면, list의 erase와 insert 함수는 O(1)의 시간이 걸려서 안전합니다!
리뷰를 남겼으니 참고하시기 바랍니다!!

2022-09-26 13:32 UTC, Dong-droid commented on [구현&코너케이스] 9월 20일/5397.cpp
> +	for (int i = 0; i < n; i++) {
p3. n을 다른 곳에서 사용하지 않을 것이기 때문에 while(n--)라고 해도 될 것 같습니다!

2022-09-26 13:33 UTC, Dong-droid commented on [구현&코너케이스] 9월 20일/5397.cpp
> +
p3. 이 조건문을 없애고 맨 마지막의 else {} 로 뺄 수 있을 것 같습니다~

2022-09-27 11:10 UTC, Lisa-Tera commented on [구현&코너케이스] 9월 20일/5397.cpp
> +	for (int i = 0; i < n; i++) {
코드를 더 간단하게 만들 수 있었네요!

2022-09-28 00:32 UTC, 0321minji reviewed
**3226 코드리뷰 완료**
안녕하세요 은서님!
작성해주신 코드 잘봤습니다!
해당 문제가 구현 문제라 여러 방법으로 풀이가 가능한데 그 중 저희가 준비한 첫번째 샘플코드와 유사하게 풀이해주셨네요👍👍
함수 사용에 있어 조그마한 코멘트 남겨드렸으니 확인부탁드려요!
또, 다른 문제 주석은 잘 보이는데 해당 문제만 주석이 깨져보이네요ㅜㅜ 열심히 작성해주셨는데 아쉬워요😥 확인해주시면 좋을 것 같아요!
수고하셨습니다🙌🙌

2022-09-28 00:32 UTC, 0321minji commented on [구현&코너케이스] 9월 20일/3226.cpp
> +		int h1 = stoi(s1), m1= stoi(s2);//���ڷ� ��ȯ 06:50 ==>h1=06    m1 =50
p3.
지금 방법도 좋지만 getline 과 구분자를 활용하여 처음부터 구분하여 입력받을 수 있답니다!
샘플코드 참고해주시면 좋을 것 같아요~!

2022-09-28 00:32 UTC, 0321minji commented on [구현&코너케이스] 9월 20일/3226.cpp
> +		}
p2.
저희 튜터링에서는 최대한 main은 간결하게 풀이의 주요한 기능은 함수로 빼서 재사용이 가능하게 권장드리고 있습니다!
물론 해당 문제풀이에서는 한 번의 조건 확인만 필요하므로 재사용할 가능성이 낮지만, 함수로 빼서 구현하는 방법에 익숙해지시면 좋을 것 같아요~!

2022-10-04 11:01 UTC, merged